# Generated by Django 2.2.12 on 2020-05-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='desc',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.TextField(max_length=60),
        ),
    ]
